#include "test_runner.h"
#include "request.h"

using namespace std;

void TestPartD() {
    istringstream input(R"({)" "\n"
        R"( "base_requests": [)" "\n"
        R"(   {)" "\n"
        R"(     "type": "Stop",)" "\n"
        R"(     "road_distances": {)" "\n"
        R"(       "Marushkino": 3900)" "\n"
        R"(     },)" "\n"
        R"(     "longitude": 37.20829,)" "\n"
        R"(     "name": "Tolstopaltsevo",)" "\n"
        R"(     "latitude": 55.611087)" "\n"
        R"(   },)" "\n"
        R"(   {)" "\n"
        R"(     "type": "Stop",)" "\n"
        R"(     "road_distances": {)" "\n"
        R"(       "Rasskazovka": 9900)" "\n"
        R"(     },)" "\n"
        R"(     "longitude": 37.209755,)" "\n"
        R"(     "name": "Marushkino",)" "\n"
        R"(     "latitude": 55.595884)" "\n"
        R"(   },)" "\n"
        R"(   {)" "\n"
        R"(     "type": "Bus",)" "\n"
        R"(     "name": "256",)" "\n"
        R"(     "stops": [)" "\n"
        R"(       "Biryulyovo Zapadnoye",)" "\n"
        R"(       "Biryusinka",)" "\n"
        R"(       "Universam",)" "\n"
        R"(       "Biryulyovo Tovarnaya",)" "\n"
        R"(       "Biryulyovo Passazhirskaya",)" "\n"
        R"(       "Biryulyovo Zapadnoye")" "\n"
        R"(     ] ,)" "\n"
        R"(     "is_roundtrip": true)" "\n"
        R"(   },)" "\n"
        R"(   {)" "\n"
        R"(     "type": "Bus",)" "\n"
        R"(     "name": "750",)" "\n"
        R"(     "stops": [)" "\n"
        R"(       "Tolstopaltsevo",)" "\n"
        R"(       "Marushkino",)" "\n"
        R"(       "Rasskazovka")" "\n"
        R"(     ] ,)" "\n"
        R"(     "is_roundtrip": false)" "\n"
        R"(   },)" "\n"
        R"(   {)" "\n"
        R"(     "type": "Stop",)" "\n"
        R"(     "road_distances": {},)" "\n"
        R"(     "longitude": 37.333324,)" "\n"
        R"(     "name": "Rasskazovka",)" "\n"
        R"(     "latitude": 55.632761)" "\n"
        R"(   },)" "\n"
        R"(   {)" "\n"
        R"(     "type": "Stop",)" "\n"
        R"(     "road_distances": {)" "\n"
        R"(       "Rossoshanskaya ulitsa": 7500,)" "\n"
        R"(       "Biryusinka": 1800,)" "\n"
        R"(       "Universam": 2400)" "\n"
        R"(     },)" "\n"
        R"(     "longitude": 37.6517,)" "\n"
        R"(     "name": "Biryulyovo Zapadnoye",)" "\n"
        R"(     "latitude": 55.574371)" "\n"
        R"(   },)" "\n"
        R"(   {)" "\n"
        R"(     "type": "Stop",)" "\n"
        R"(     "road_distances": {)" "\n"
        R"(       "Universam": 750)" "\n"
        R"(     },)" "\n"
        R"(     "longitude": 37.64839,)" "\n"
        R"(     "name": "Biryusinka",)" "\n"
        R"(     "latitude": 55.581065)" "\n"
        R"(   },)" "\n"
        R"(   {)" "\n"
        R"(     "type": "Stop",)" "\n"
        R"(     "road_distances": {)" "\n"
        R"(       "Rossoshanskaya ulitsa": 5600,)" "\n"
        R"(       "Biryulyovo Tovarnaya": 900)" "\n"
        R"(     },)" "\n"
        R"(     "longitude": 37.645687,)" "\n"
        R"(     "name": "Universam",)" "\n"
        R"(     "latitude": 55.587655)" "\n"
        R"(   },)" "\n"
        R"(   {)" "\n"
        R"(     "type": "Stop",)" "\n"
        R"(     "road_distances": {)" "\n"
        R"(       "Biryulyovo Passazhirskaya": 1300)" "\n"
        R"(     },)" "\n"
        R"(     "longitude": 37.653656,)" "\n"
        R"(     "name": "Biryulyovo Tovarnaya",)" "\n"
        R"(     "latitude": 55.592028)" "\n"
        R"(   },)" "\n"
        R"(   {)" "\n"
        R"(     "type": "Stop",)" "\n"
        R"(     "road_distances": {)" "\n"
        R"(       "Biryulyovo Zapadnoye": 1200)" "\n"
        R"(     },)" "\n"
        R"(     "longitude": 37.659164,)" "\n"
        R"(     "name": "Biryulyovo Passazhirskaya",)" "\n"
        R"(     "latitude": 55.580999)" "\n"
        R"(   },)" "\n"
        R"(   {)" "\n"
        R"(     "type": "Bus",)" "\n"
        R"(     "name": "828",)" "\n"
        R"(     "stops": [)" "\n"
        R"(       "Biryulyovo Zapadnoye",)" "\n"
        R"(       "Universam",)" "\n"
        R"(       "Rossoshanskaya ulitsa",)" "\n"
        R"(       "Biryulyovo Zapadnoye")" "\n"
        R"(     ] ,)" "\n"
        R"(     "is_roundtrip": true)" "\n"
        R"(   },)" "\n"
        R"(   {)" "\n"
        R"(     "type": "Stop",)" "\n"
        R"(     "road_distances": {},)" "\n"
        R"(     "longitude": 37.605757,)" "\n"
        R"(     "name": "Rossoshanskaya ulitsa",)" "\n"
        R"(     "latitude": 55.595579)" "\n"
        R"(   },)" "\n"
        R"(   {)" "\n"
        R"(     "type": "Stop",)" "\n"
        R"(     "road_distances": {},)" "\n"
        R"(     "longitude": 37.603831,)" "\n"
        R"(     "name": "Prazhskaya",)" "\n"
        R"(     "latitude": 55.611678)" "\n"
        R"(   })" "\n"
        R"( ],)" "\n"
        R"( "stat_requests": [)" "\n"
        R"(   {)" "\n"
        R"(     "type": "Bus",)" "\n"
        R"(     "name": "256",)" "\n"
        R"(     "id": 1965312327)" "\n"
        R"(   },)" "\n"
        R"(   {)" "\n"
        R"(     "type": "Bus",)" "\n"
        R"(     "name": "750",)" "\n"
        R"(     "id": 519139350)" "\n"
        R"(   },)" "\n"
        R"(   {)" "\n"
        R"(     "type": "Bus",)" "\n"
        R"(     "name": "751",)" "\n"
        R"(     "id": 194217464)" "\n"
        R"(   },)" "\n"
        R"(   {)" "\n"
        R"(     "type": "Stop",)" "\n"
        R"(     "name": "Samara",)" "\n"
        R"(     "id": 746888088)" "\n"
        R"(   },)" "\n"
        R"(   {)" "\n"
        R"(     "type": "Stop",)" "\n"
        R"(     "name": "Prazhskaya",)" "\n"
        R"(     "id": 65100610)" "\n"
        R"(   },)" "\n"
        R"(   {)" "\n"
        R"(     "type": "Stop",)" "\n"
        R"(     "name": "Biryulyovo Zapadnoye",)" "\n"
        R"(     "id": 1042838872)" "\n"
        R"(   })" "\n"
        R"( ])" "\n"
        R"(})"
    );

    using namespace Request::Handler;
    const auto requests = Read(input);
    const auto responses = Process(requests);
    ostringstream output;
    output << responses;

    string result(
        R"([)" "\n"
        R"({)" "\n"
        R"("curvature": 1.361239,)" "\n"
        R"("request_id": 1965312327,)" "\n"
        R"("route_length": 5950,)" "\n"
        R"("stop_count": 6,)" "\n"
        R"("unique_stop_count": 5)" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("curvature": 1.318084,)" "\n"
        R"("request_id": 519139350,)" "\n"
        R"("route_length": 27600,)" "\n"
        R"("stop_count": 5,)" "\n"
        R"("unique_stop_count": 3)" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("error_message": "not found",)" "\n"
        R"("request_id": 194217464)" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("error_message": "not found",)" "\n"
        R"("request_id": 746888088)" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("buses": [)" "\n"
        R"(],)" "\n"
        R"("request_id": 65100610)" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("buses": [)" "\n"
        R"("256",)" "\n"
        R"("828")" "\n"
        R"(],)" "\n"
        R"("request_id": 1042838872)" "\n"
        R"(})" "\n"
        R"(])");
    ASSERT_EQUAL(output.str(), result);
}

void TestPartE1() {
    istringstream input(R"({)" "\n"
        R"(  "routing_settings": {)" "\n"
        R"(    "bus_wait_time": 6,)" "\n"
        R"(    "bus_velocity": 40)" "\n"
        R"(  },)" "\n"
        R"(  "base_requests": [)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Bus",)" "\n"
        R"(      "name": "297",)" "\n"
        R"(      "stops": [)" "\n"
        R"(        "Biryulyovo Zapadnoye",)" "\n"
        R"(        "Biryulyovo Tovarnaya",)" "\n"
        R"(        "Universam",)" "\n"
        R"(        "Biryulyovo Zapadnoye")" "\n"
        R"(      ] ,)" "\n"
        R"(      "is_roundtrip": true)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Bus",)" "\n"
        R"(      "name": "635",)" "\n"
        R"(      "stops": [)" "\n"
        R"(        "Biryulyovo Tovarnaya",)" "\n"
        R"(        "Universam",)" "\n"
        R"(        "Prazhskaya")" "\n"
        R"(      ] ,)" "\n"
        R"(      "is_roundtrip": false)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Stop",)" "\n"
        R"(      "road_distances": {)" "\n"
        R"(        "Biryulyovo Tovarnaya": 2600)" "\n"
        R"(      },)" "\n"
        R"(      "longitude": 37.6517,)" "\n"
        R"(      "name": "Biryulyovo Zapadnoye",)" "\n"
        R"(      "latitude": 55.574371)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Stop",)" "\n"
        R"(      "road_distances": {)" "\n"
        R"(        "Prazhskaya": 4650,)" "\n"
        R"(        "Biryulyovo Tovarnaya": 1380,)" "\n"
        R"(        "Biryulyovo Zapadnoye": 2500)" "\n"
        R"(      },)" "\n"
        R"(      "longitude": 37.645687,)" "\n"
        R"(      "name": "Universam",)" "\n"
        R"(      "latitude": 55.587655)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Stop",)" "\n"
        R"(      "road_distances": {)" "\n"
        R"(        "Universam": 890)" "\n"
        R"(      },)" "\n"
        R"(      "longitude": 37.653656,)" "\n"
        R"(      "name": "Biryulyovo Tovarnaya",)" "\n"
        R"(      "latitude": 55.592028)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Stop",)" "\n"
        R"(      "road_distances": {},)" "\n"
        R"(      "longitude": 37.603938,)" "\n"
        R"(      "name": "Prazhskaya",)" "\n"
        R"(      "latitude": 55.611717)" "\n"
        R"(    })" "\n"
        R"(  ],)" "\n"
        R"(  "stat_requests": [)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Bus",)" "\n"
        R"(      "name": "297",)" "\n"
        R"(      "id": 1)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Bus",)" "\n"
        R"(      "name": "635",)" "\n"
        R"(      "id": 2)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Stop",)" "\n"
        R"(      "name": "Universam",)" "\n"
        R"(      "id": 3)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Route",)" "\n"
        R"(      "from": "Biryulyovo Zapadnoye",)" "\n"
        R"(      "to": "Universam",)" "\n"
        R"(      "id": 4)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Route",)" "\n"
        R"(      "from": "Biryulyovo Zapadnoye",)" "\n"
        R"(      "to": "Prazhskaya",)" "\n"
        R"(      "id": 5)" "\n"
        R"(    })" "\n"
        R"(  ])" "\n"
        R"(})"
    );

    using namespace Request::Handler;
    const auto requests = Read(input);
    const auto responses = Process(requests);
    ostringstream output;
    output << responses;

    string result(
        R"([)" "\n"
        R"({)" "\n"
        R"("curvature": 1.429627,)" "\n"
        R"("request_id": 1,)" "\n"
        R"("route_length": 5990,)" "\n"
        R"("stop_count": 4,)" "\n"
        R"("unique_stop_count": 3)" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("curvature": 1.30156,)" "\n"
        R"("request_id": 2,)" "\n"
        R"("route_length": 11570,)" "\n"
        R"("stop_count": 5,)" "\n"
        R"("unique_stop_count": 3)" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("buses": [)" "\n"
        R"("297",)" "\n"
        R"("635")" "\n"
        R"(],)" "\n"
        R"("request_id": 3)" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("items": [)" "\n"
        R"({)" "\n"
        R"("stop_name": "Biryulyovo Zapadnoye",)" "\n"
        R"("time": 6,)" "\n"
        R"("type": "Wait")" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("bus": "297",)" "\n"
        R"("span_count": 2,)" "\n"
        R"("time": 5.235,)" "\n"
        R"("type": "Bus")" "\n"
        R"(})" "\n"
        R"(],)" "\n"
        R"("request_id": 4,)" "\n"
        R"("total_time": 11.235)" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("items": [)" "\n"
        R"({)" "\n"
        R"("stop_name": "Biryulyovo Zapadnoye",)" "\n"
        R"("time": 6,)" "\n"
        R"("type": "Wait")" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("bus": "297",)" "\n"
        R"("span_count": 1,)" "\n"
        R"("time": 3.9,)" "\n"
        R"("type": "Bus")" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("stop_name": "Biryulyovo Tovarnaya",)" "\n"
        R"("time": 6,)" "\n"
        R"("type": "Wait")" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("bus": "635",)" "\n"
        R"("span_count": 2,)" "\n"
        R"("time": 8.31,)" "\n"
        R"("type": "Bus")" "\n"
        R"(})" "\n"
        R"(],)" "\n"
        R"("request_id": 5,)" "\n"
        R"("total_time": 24.21)" "\n"
        R"(})" "\n"
        R"(])"
    );
    ASSERT_EQUAL(output.str(), result);
}

void TestPartE2() {
    istringstream input(
        R"({)" "\n"
        R"(  "routing_settings": {)" "\n"
        R"(    "bus_wait_time": 2,)" "\n"
        R"(    "bus_velocity": 30)" "\n"
        R"(  },)" "\n"
        R"(  "base_requests": [)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Bus",)" "\n"
        R"(      "name": "297",)" "\n"
        R"(      "stops": [)" "\n"
        R"(        "Biryulyovo Zapadnoye",)" "\n"
        R"(        "Biryulyovo Tovarnaya",)" "\n"
        R"(        "Universam",)" "\n"
        R"(        "Biryusinka",)" "\n"
        R"(        "Apteka",)" "\n"
        R"(        "Biryulyovo Zapadnoye")" "\n"
        R"(      ],)" "\n"
        R"(      "is_roundtrip": true)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Bus",)" "\n"
        R"(      "name": "635",)" "\n"
        R"(      "stops": [)" "\n"
        R"(        "Biryulyovo Tovarnaya",)" "\n"
        R"(        "Universam",)" "\n"
        R"(        "Biryusinka",)" "\n"
        R"(        "TETs 26",)" "\n"
        R"(        "Pokrovskaya",)" "\n"
        R"(        "Prazhskaya")" "\n"
        R"(      ],)" "\n"
        R"(      "is_roundtrip": false)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Bus",)" "\n"
        R"(      "name" : "828",)" "\n"
        R"(      "stops" : [)" "\n"
        R"(        "Biryulyovo Zapadnoye",)" "\n"
        R"(        "TETs 26",)" "\n"
        R"(        "Biryusinka",)" "\n"
        R"(        "Universam",)" "\n"
        R"(        "Pokrovskaya",)" "\n"
        R"(        "Rossoshanskaya ulitsa")" "\n"
        R"(      ],)" "\n"
        R"(      "is_roundtrip": false)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Stop",)" "\n"
        R"(      "road_distances": {)" "\n"
        R"(        "Biryulyovo Tovarnaya": 2600,)" "\n"
        R"(        "TETs 26": 1100)" "\n"
        R"(      },)" "\n"
        R"(      "longitude": 37.6517,)" "\n"
        R"(      "name": "Biryulyovo Zapadnoye",)" "\n"
        R"(      "latitude": 55.574371)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Stop",)" "\n"
        R"(      "road_distances": {)" "\n"
        R"(        "Biryusinka": 760,)" "\n"
        R"(        "Biryulyovo Tovarnaya": 1380,)" "\n"
        R"(        "Pokrovskaya": 2460)" "\n"
        R"(      },)" "\n"
        R"(      "longitude": 37.645687,)" "\n"
        R"(      "name": "Universam",)" "\n"
        R"(      "latitude": 55.587655)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Stop",)" "\n"
        R"(      "road_distances": {)" "\n"
        R"(        "Universam": 890)" "\n"
        R"(      },)" "\n"
        R"(      "longitude": 37.653656,)" "\n"
        R"(      "name": "Biryulyovo Tovarnaya",)" "\n"
        R"(      "latitude": 55.592028)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Stop",)" "\n"
        R"(      "road_distances": {)" "\n"
        R"(        "Apteka": 210,)" "\n"
        R"(        "TETs 26": 400)" "\n"
        R"(      },)" "\n"
        R"(      "longitude": 37.64839,)" "\n"
        R"(      "name": "Biryusinka",)" "\n"
        R"(      "latitude": 55.581065)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Stop",)" "\n"
        R"(      "road_distances": {)" "\n"
        R"(        "Biryulyovo Zapadnoye": 1420)" "\n"
        R"(      },)" "\n"
        R"(      "longitude": 37.652296,)" "\n"
        R"(      "name": "Apteka",)" "\n"
        R"(      "latitude": 55.580023)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Stop",)" "\n"
        R"(      "road_distances": {)" "\n"
        R"(        "Pokrovskaya": 2850)" "\n"
        R"(      },)" "\n"
        R"(      "longitude": 37.642258,)" "\n"
        R"(      "name": "TETs 26",)" "\n"
        R"(      "latitude": 55.580685)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Stop",)" "\n"
        R"(      "road_distances": {)" "\n"
        R"(        "Rossoshanskaya ulitsa": 3140)" "\n"
        R"(      },)" "\n"
        R"(      "longitude": 37.635517,)" "\n"
        R"(      "name": "Pokrovskaya",)" "\n"
        R"(      "latitude": 55.603601)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Stop",)" "\n"
        R"(      "road_distances": {)" "\n"
        R"(        "Pokrovskaya": 3210)" "\n"
        R"(      },)" "\n"
        R"(      "longitude": 37.605757,)" "\n"
        R"(      "name": "Rossoshanskaya ulitsa",)" "\n"
        R"(      "latitude": 55.595579)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Stop",)" "\n"
        R"(      "road_distances": {)" "\n"
        R"(        "Pokrovskaya": 2260)" "\n"
        R"(      },)" "\n"
        R"(      "longitude": 37.603938,)" "\n"
        R"(      "name": "Prazhskaya",)" "\n"
        R"(      "latitude": 55.611717)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Bus",)" "\n"
        R"(      "name": "750",)" "\n"
        R"(      "stops": [)" "\n"
        R"(        "Tolstopaltsevo",)" "\n"
        R"(        "Rasskazovka")" "\n"
        R"(      ],)" "\n"
        R"(      "is_roundtrip": false)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Stop",)" "\n"
        R"(      "road_distances": {)" "\n"
        R"(        "Rasskazovka": 13800)" "\n"
        R"(      },)" "\n"
        R"(      "longitude": 37.20829,)" "\n"
        R"(      "name": "Tolstopaltsevo",)" "\n"
        R"(      "latitude": 55.611087)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Stop",)" "\n"
        R"(      "road_distances": {},)" "\n"
        R"(      "longitude": 37.333324,)" "\n"
        R"(      "name": "Rasskazovka",)" "\n"
        R"(      "latitude": 55.632761)" "\n"
        R"(    })" "\n"
        R"(  ],)" "\n"
        R"(  "stat_requests": [)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Bus",)" "\n"
        R"(      "name": "297",)" "\n"
        R"(      "id": 1)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Bus",)" "\n"
        R"(      "name": "635",)" "\n"
        R"(      "id": 2)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Bus",)" "\n"
        R"(      "name": "828",)" "\n"
        R"(      "id": 3)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Stop",)" "\n"
        R"(      "name": "Universam",)" "\n"
        R"(      "id": 4)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Route",)" "\n"
        R"(      "from": "Biryulyovo Zapadnoye",)" "\n"
        R"(      "to": "Apteka",)" "\n"
        R"(      "id": 5)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Route",)" "\n"
        R"(      "from": "Biryulyovo Zapadnoye",)" "\n"
        R"(      "to": "Pokrovskaya",)" "\n"
        R"(      "id": 6)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Route",)" "\n"
        R"(      "from": "Biryulyovo Tovarnaya",)" "\n"
        R"(      "to": "Pokrovskaya",)" "\n"
        R"(      "id": 7)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Route",)" "\n"
        R"(      "from": "Biryulyovo Tovarnaya",)" "\n"
        R"(      "to": "Biryulyovo Zapadnoye",)" "\n"
        R"(      "id": 8)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Route",)" "\n"
        R"(      "from": "Biryulyovo Tovarnaya",)" "\n"
        R"(      "to": "Prazhskaya",)" "\n"
        R"(      "id": 9)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Route",)" "\n"
        R"(      "from": "Apteka",)" "\n"
        R"(      "to": "Biryulyovo Tovarnaya",)" "\n"
        R"(      "id": 10)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Route",)" "\n"
        R"(      "from": "Biryulyovo Zapadnoye",)" "\n"
        R"(      "to": "Tolstopaltsevo",)" "\n"
        R"(      "id": 11)" "\n"
        R"(    })" "\n"
        R"(  ])" "\n"
        R"(})"
    );

    using namespace Request::Handler;
    const auto requests = Read(input);
    const auto responses = Process(requests);
    ostringstream output;
    output << responses;

    string result(
        R"([)" "\n"
        R"({)" "\n"
        R"("curvature": 1.361591,)" "\n"
        R"("request_id": 1,)" "\n"
        R"("route_length": 5880,)" "\n"
        R"("stop_count": 6,)" "\n"
        R"("unique_stop_count": 5)" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("curvature": 1.121947,)" "\n"
        R"("request_id": 2,)" "\n"
        R"("route_length": 14810,)" "\n"
        R"("stop_count": 11,)" "\n"
        R"("unique_stop_count": 6)" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("curvature": 1.312451,)" "\n"
        R"("request_id": 3,)" "\n"
        R"("route_length": 15790,)" "\n"
        R"("stop_count": 11,)" "\n"
        R"("unique_stop_count": 6)" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("buses": [)" "\n"
        R"("297",)" "\n"
        R"("635",)" "\n"
        R"("828")" "\n"
        R"(],)" "\n"
        R"("request_id": 4)" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("items": [)" "\n"
        R"({)" "\n"
        R"("stop_name": "Biryulyovo Zapadnoye",)" "\n"
        R"("time": 2,)" "\n"
        R"("type": "Wait")" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("bus": "828",)" "\n"
        R"("span_count": 2,)" "\n"
        R"("time": 3,)" "\n"
        R"("type": "Bus")" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("stop_name": "Biryusinka",)" "\n"
        R"("time": 2,)" "\n"
        R"("type": "Wait")" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("bus": "297",)" "\n"
        R"("span_count": 1,)" "\n"
        R"("time": 0.42,)" "\n"
        R"("type": "Bus")" "\n"
        R"(})" "\n"
        R"(],)" "\n"
        R"("request_id": 5,)" "\n"
        R"("total_time": 7.42)" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("items": [)" "\n"
        R"({)" "\n"
        R"("stop_name": "Biryulyovo Zapadnoye",)" "\n"
        R"("time": 2,)" "\n"
        R"("type": "Wait")" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("bus": "828",)" "\n"
        R"("span_count": 4,)" "\n"
        R"("time": 9.44,)" "\n"
        R"("type": "Bus")" "\n"
        R"(})" "\n"
        R"(],)" "\n"
        R"("request_id": 6,)" "\n"
        R"("total_time": 11.44)" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("items": [)" "\n"
        R"({)" "\n"
        R"("stop_name": "Biryulyovo Tovarnaya",)" "\n"
        R"("time": 2,)" "\n"
        R"("type": "Wait")" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("bus": "635",)" "\n"
        R"("span_count": 1,)" "\n"
        R"("time": 1.78,)" "\n"
        R"("type": "Bus")" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("stop_name": "Universam",)" "\n"
        R"("time": 2,)" "\n"
        R"("type": "Wait")" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("bus": "828",)" "\n"
        R"("span_count": 1,)" "\n"
        R"("time": 4.92,)" "\n"
        R"("type": "Bus")" "\n"
        R"(})" "\n"
        R"(],)" "\n"
        R"("request_id": 7,)" "\n"
        R"("total_time": 10.7)" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("items": [)" "\n"
        R"({)" "\n"
        R"("stop_name": "Biryulyovo Tovarnaya",)" "\n"
        R"("time": 2,)" "\n"
        R"("type": "Wait")" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("bus": "297",)" "\n"
        R"("span_count": 4,)" "\n"
        R"("time": 6.56,)" "\n"
        R"("type": "Bus")" "\n"
        R"(})" "\n"
        R"(],)" "\n"
        R"("request_id": 8,)" "\n"
        R"("total_time": 8.56)" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("items": [)" "\n"
        R"({)" "\n"
        R"("stop_name": "Biryulyovo Tovarnaya",)" "\n"
        R"("time": 2,)" "\n"
        R"("type": "Wait")" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("bus": "635",)" "\n"
        R"("span_count": 5,)" "\n"
        R"("time": 14.32,)" "\n"
        R"("type": "Bus")" "\n"
        R"(})" "\n"
        R"(],)" "\n"
        R"("request_id": 9,)" "\n"
        R"("total_time": 16.32)" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("items": [)" "\n"
        R"({)" "\n"
        R"("stop_name": "Apteka",)" "\n"
        R"("time": 2,)" "\n"
        R"("type": "Wait")" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("bus": "297",)" "\n"
        R"("span_count": 1,)" "\n"
        R"("time": 2.84,)" "\n"
        R"("type": "Bus")" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("stop_name": "Biryulyovo Zapadnoye",)" "\n"
        R"("time": 2,)" "\n"
        R"("type": "Wait")" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("bus": "297",)" "\n"
        R"("span_count": 1,)" "\n"
        R"("time": 5.2,)" "\n"
        R"("type": "Bus")" "\n"
        R"(})" "\n"
        R"(],)" "\n"
        R"("request_id": 10,)" "\n"
        R"("total_time": 12.04)" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("error_message": "not found",)" "\n"
        R"("request_id": 11)" "\n"
        R"(})" "\n"
        R"(])"
    );
    ASSERT_EQUAL(output.str(), result);
}

void TestPartE3() {
    istringstream input(
        R"({)" "\n"
        R"(  "routing_settings": {)" "\n"
        R"(    "bus_wait_time": 2,)" "\n"
        R"(    "bus_velocity": 30)" "\n"
        R"(  },)" "\n"
        R"(  "base_requests": [)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Bus",)" "\n"
        R"(      "name": "289",)" "\n"
        R"(      "stops": [)" "\n"
        R"(        "Zagorye",)" "\n"
        R"(        "Lipetskaya ulitsa 46",)" "\n"
        R"(        "Lipetskaya ulitsa 40",)" "\n"
        R"(        "Lipetskaya ulitsa 40",)" "\n"
        R"(        "Lipetskaya ulitsa 46",)" "\n"
        R"(        "Moskvorechye",)" "\n"
        R"(        "Zagorye")" "\n"
        R"(      ],)" "\n"
        R"(      "is_roundtrip": true)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Stop",)" "\n"
        R"(      "road_distances": {)" "\n"
        R"(        "Lipetskaya ulitsa 46": 230)" "\n"
        R"(      },)" "\n"
        R"(      "longitude": 37.68372,)" "\n"
        R"(      "name": "Zagorye",)" "\n"
        R"(      "latitude": 55.579909)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Stop",)" "\n"
        R"(      "road_distances": {)" "\n"
        R"(        "Lipetskaya ulitsa 40": 390,)" "\n"
        R"(        "Moskvorechye": 12400)" "\n"
        R"(      },)" "\n"
        R"(      "longitude": 37.682205,)" "\n"
        R"(      "name": "Lipetskaya ulitsa 46",)" "\n"
        R"(      "latitude": 55.581441)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Stop",)" "\n"
        R"(      "road_distances": {)" "\n"
        R"(        "Lipetskaya ulitsa 40": 1090,)" "\n"
        R"(        "Lipetskaya ulitsa 46": 380)" "\n"
        R"(      },)" "\n"
        R"(      "longitude": 37.679133,)" "\n"
        R"(      "name": "Lipetskaya ulitsa 40",)" "\n"
        R"(      "latitude": 55.584496)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Stop",)" "\n"
        R"(      "road_distances": {)" "\n"
        R"(        "Zagorye": 10000)" "\n"
        R"(      },)" "\n"
        R"(      "longitude": 37.638433,)" "\n"
        R"(      "name": "Moskvorechye",)" "\n"
        R"(      "latitude": 55.638433)" "\n"
        R"(    })" "\n"
        R"(  ],)" "\n"
        R"(  "stat_requests": [)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Bus",)" "\n"
        R"(      "name": "289",)" "\n"
        R"(      "id": 1)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Route",)" "\n"
        R"(      "from": "Zagorye",)" "\n"
        R"(      "to": "Moskvorechye",)" "\n"
        R"(      "id": 2)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Route",)" "\n"
        R"(      "from": "Moskvorechye",)" "\n"
        R"(      "to": "Zagorye",)" "\n"
        R"(      "id": 3)" "\n"
        R"(    },)" "\n"
        R"(    {)" "\n"
        R"(      "type": "Route",)" "\n"
        R"(      "from": "Lipetskaya ulitsa 40",)" "\n"
        R"(      "to": "Lipetskaya ulitsa 40",)" "\n"
        R"(      "id": 4)" "\n"
        R"(    })" "\n"
        R"(  ])" "\n"
        R"(})"
    );

    using namespace Request::Handler;
    const auto requests = Read(input);
    const auto responses = Process(requests);
    ostringstream output;
    output << responses;

    string result(
        R"([)" "\n"
        R"({)" "\n"
        R"("curvature": 1.63414,)" "\n"
        R"("request_id": 1,)" "\n"
        R"("route_length": 24490,)" "\n"
        R"("stop_count": 7,)" "\n"
        R"("unique_stop_count": 4)" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("items": [)" "\n"
        R"({)" "\n"
        R"("stop_name": "Zagorye",)" "\n"
        R"("time": 2,)" "\n"
        R"("type": "Wait")" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("bus": "289",)" "\n"
        R"("span_count": 1,)" "\n"
        R"("time": 0.46,)" "\n"
        R"("type": "Bus")" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("stop_name": "Lipetskaya ulitsa 46",)" "\n"
        R"("time": 2,)" "\n"
        R"("type": "Wait")" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("bus": "289",)" "\n"
        R"("span_count": 1,)" "\n"
        R"("time": 24.8,)" "\n"
        R"("type": "Bus")" "\n"
        R"(})" "\n"
        R"(],)" "\n"
        R"("request_id": 2,)" "\n"
        R"("total_time": 29.26)" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("items": [)" "\n"
        R"({)" "\n"
        R"("stop_name": "Moskvorechye",)" "\n"
        R"("time": 2,)" "\n"
        R"("type": "Wait")" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("bus": "289",)" "\n"
        R"("span_count": 1,)" "\n"
        R"("time": 20,)" "\n"
        R"("type": "Bus")" "\n"
        R"(})" "\n"
        R"(],)" "\n"
        R"("request_id": 3,)" "\n"
        R"("total_time": 22)" "\n"
        R"(},)" "\n"
        R"({)" "\n"
        R"("items": [)" "\n"
        R"(],)" "\n"
        R"("request_id": 4,)" "\n"
        R"("total_time": 0)" "\n"
        R"(})" "\n"
        R"(])"
    );
    ASSERT_EQUAL(output.str(), result);
}

void TestAll() {
    TestRunner tr;
    RUN_TEST(tr, TestPartD);
    RUN_TEST(tr, TestPartE1);
    RUN_TEST(tr, TestPartE2);
    RUN_TEST(tr, TestPartE3);
}

int main() {
    TestAll();

    using namespace Request::Handler;
    try {
        const auto requests = Read();
        const auto responses = Process(requests);
        cout << responses;
    }
    catch (const exception& ex) {
        cout << ex.what();
    }
    return 0;
}
